// <auto-generated />
namespace TyoaikaApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Testi6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Testi6));
        
        string IMigrationMetadata.Id
        {
            get { return "201504221646444_Testi6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
